# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxGrailed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxGrailed
  pod 'AlgoliaSearch-Client-Swift', '~> 4.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Action'
  pod 'ModelMapper'
  pod 'Kingfisher'

  target 'RxGrailedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
